const { MessageBox } = require('element-ui');

MessageBox.setDefaults({
	title: '',
	message: '',
	type: '',
	iconClass: '',
	showInput: false,
	showClose: true,
	modalFade: true,
	lockScroll: true,
	closeOnClickModal: true,
	closeOnPressEscape: true,
	closeOnHashChange: true,
	inputValue: null,
	inputPlaceholder: '',
	inputType: 'text',
	inputPattern: null,
	inputValidator: null,
	inputErrorMessage: '',
	showConfirmButton: true,
	showCancelButton: false,
	confirmButtonPosition: 'right',
	confirmButtonHighlight: false,
	cancelButtonHighlight: false,
	confirmButtonText: '',
	cancelButtonText: '',
	confirmButtonClass: 'at-button',
	cancelButtonClass: 'at-button',
	customClass: 'at-message-box',
	beforeClose: null,
	dangerouslyUseHTMLString: false,
	center: false,
	roundButton: false,
	distinguishCancelAndClose: false
});
